### ISSUE TITLE
Pinging Check

### ISSUE THREAD

**Issue by sagostin** [netwatcherio/netwatcher-agent#12]
Its quite trivial to create and aggregate standard ICMP pings. You can use Go's built in golang.org/x/net/icmp package for creating and parsing requests. You can see an example or sending and receiving multiple pings asynchronously here: https://github.com/bradenn/udap/blob/33a6c7ccf72d8cec9f30459bf5f66353959757f0/modules/vyos/vyos.go#L140C43-L140C43

_Originally posted by @bradenn in https://github.com/netwatcherio/netwatcher-agent/issues/4#issuecomment-1644714129_

**Comment by sagostin** [comment]
@bradenn I had considered using Go's standard ICMP package, however after doing some research, I found this. 
https://github.com/prometheus-community/pro-bing
What are your thoughts on it? I've played around with it a bit, but haven't fully implemented it the way I would like.

**Comment by bradenn** [comment]
> 

It looks like a wrapper of the built in stuff. It seems to reliably handle the woes of Windows. I'm not a fan of the callback functions but it should work fine. I'm also not sure how reliable it would be with many concurrent pings. Its not a singlet, so each ping will open a new connection.

**Comment by sagostin** [comment]
> It looks like a wrapper of the built in stuff. It seems to reliably handle the woes of Windows. I'm not a fan of the callback functions but it should work fine. I'm also not sure how reliable it would be with many concurrent pings. Its not a singlet, so each ping will open a new connection.

Gotcha, that would likely cause some issues if we added a bunch of hosts to check... got any ideas on how we could improve that? Ideally it will support Windows, Linux and Mac in the end. And by each ping do you mean each single ping like if we ran it for 60 seconds, it would be 60 new connections? Just setting those connections up will take time... hmm...

**Comment by bradenn** [comment]
> > It looks like a wrapper of the built in stuff. It seems to reliably handle the woes of Windows. I'm not a fan of the callback functions but it should work fine. I'm also not sure how reliable it would be with many concurrent pings. Its not a singlet, so each ping will open a new connection.
> 
> Gotcha, that would likely cause some issues if we added a bunch of hosts to check... got any ideas on how we could improve that? Ideally it will support Windows, Linux and Mac in the end. And by each ping do you mean each single ping like if we ran it for 60 seconds, it would be 60 new connections? Just setting those connections up will take time... hmm...

If you have 10 hosts and and ping them once a second for 60 seconds, it will create 10 connections.
