### ISSUE TITLE
Websockets?

### ISSUE THREAD

**Issue by sagostin** [netwatcherio/netwatcher-agent#9]
Switch to websockets for primary communication between the backend and agent for the statistical data. Other requests are completed by using normal REST API.

**Comment by bradenn** [comment]
I thought we already migrated it over to WebSockets back in January? Maybe I never pushed that code... I remember writing the code for the JWT header authentication. It should be trivial to migrate long polling to web sockets if the Vue interface is still in use.

**Comment by sagostin** [comment]
> I thought we already migrated it over to WebSockets back in January? Maybe I never pushed that code... I remember writing the code for the JWT header authentication. It should be trivial to migrate long polling to web sockets if the Vue interface is still in use.

Websockets were implemented for the frontend w/ VueJS, but not the Agent, we're still using the normal REST requests for all the data to/from the agent.

**Comment by bradenn** [comment]
It should be relatively trivial to convert it, but it'll be a chore to decide whether to keep or replace the existing server side endpoints.

**Comment by sagostin** [comment]
> It should be relatively trivial to convert it, but it'll be a chore to decide whether to keep or replace the existing server side endpoints.

Yeah, I figured as much, though I think grabbing the config and that sort of thing could still be done via REST and just the upload of data to backend using WebSockets. What do you think?

**Comment by bradenn** [comment]
> > It should be relatively trivial to convert it, but it'll be a chore to decide whether to keep or replace the existing server side endpoints.
> 
> Yeah, I figured as much, though I think grabbing the config and that sort of thing could still be done via REST and just the upload of data to backend using WebSockets. What do you think?

Well, any data that changes regularly would be over sockets. Basic configurations or data changed by user actions can be updated by rest.
